using System;
using System.Linq;
using System.Collections.Generic;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using Mutagen.Bethesda.FormKeys.SkyrimSE;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Noggog;
using NPCStatRescaler.Settings;

namespace NPCStatRescaler
{
    public class Program
    {
        private const int SurvivalCarryWeightBonus = 100;
        private const string VokriiMagickaRecoveryEffectEditorId = "VKR_Res_MagickaRecovery_Effect_Ab";
        private static Lazy<Config> _settings = null!;
        private static ILoadOrder<IModListing<ISkyrimModGetter>> _loadOrder = null!;
        private static ISkyrimMod _patchMod = null!;
        private static ILinkCache<ISkyrimMod, ISkyrimModGetter> _linkCache = null!;
        private static Spell _healthRegenAbility = null!;

        /// <summary>
        /// Splits and normalizes pattern entries.
        /// Supports both separate list entries and comma-separated values.
        /// Leading "!" is ignored so users can type "!Dragon" if they want.
        /// </summary>
        private static IEnumerable<string> EnumeratePatterns(List<string> patterns)
        {
            foreach (var rawPattern in patterns)
            {
                if (string.IsNullOrWhiteSpace(rawPattern))
                    continue;

                foreach (var splitPattern in rawPattern.Split(','))
                {
                    var pattern = splitPattern.Trim();
                    if (pattern.StartsWith("!"))
                        pattern = pattern.Substring(1).Trim();

                    if (!string.IsNullOrWhiteSpace(pattern))
                        yield return pattern;
                }
            }
        }

        private static bool MatchesAnyPattern(string editorId, List<string> patterns)
        {
            foreach (var pattern in EnumeratePatterns(patterns))
            {
                if (editorId.Contains(pattern, StringComparison.OrdinalIgnoreCase))
                    return true;
            }

            return false;
        }

        private static bool HasAnyPattern(List<string> patterns)
        {
            foreach (var _ in EnumeratePatterns(patterns))
                return true;

            return false;
        }

        /// <summary>
        /// Decides if a record should be patched.
        /// includePatterns = patterns to skip patching
        /// excludePatterns = exceptions to skip list (these records are patched)
        /// </summary>
        private static bool ShouldPatchRecord(string? editorId, List<string> includePatterns, List<string> excludePatterns)
        {
            if (string.IsNullOrWhiteSpace(editorId))
                return true;

            if (MatchesAnyPattern(editorId, excludePatterns))
                return true;

            if (!HasAnyPattern(includePatterns))
                return true;

            return !MatchesAnyPattern(editorId, includePatterns);
        }

        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("settings", "settings.json", out _settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "NPC Stat Rescaler.esp")
                .Run(args);
        }

        private static void CreateAbility()
        {
            var playableRaceRegenDebuff = _settings.Value.UsingSurvivalMode
                ? 0f
                : _settings.Value.HealthRegen.PlayableRaceHealthRegenDebuff;

            var healthRegenAbility = _patchMod.Spells.AddNew("NPC_stat_rescaler_health_regen_ability");
            healthRegenAbility.EquipmentType = Skyrim.EquipType.EitherHand.AsNullable();
            healthRegenAbility.Name = "Health Regen";
            healthRegenAbility.BaseCost = 23337;
            healthRegenAbility.Type = SpellType.Ability;
            healthRegenAbility.ChargeTime = 0.5f;
            healthRegenAbility.Effects.Add(new Effect
            {
                BaseEffect = Skyrim.MagicEffect.AbDamageHealRate.AsNullable(),
                Data = new EffectData {Magnitude = 100 * playableRaceRegenDebuff}
            });
            _healthRegenAbility = healthRegenAbility;
        }

        private static void PatchClasses()
        {
            foreach (IClassGetter classRecord in _loadOrder.PriorityOrder.Class().WinningOverrides())
            {
                if (!ShouldPatchRecord(classRecord.EditorID, _settings.Value.ClassesToInclude,
                        _settings.Value.ClassesToExclude))
                    continue;

                var classCopy = _patchMod.Classes.GetOrAddAsOverride(classRecord);
                classCopy.StatWeights[BasicStat.Health] =
                    (byte) Math.Round(classCopy.StatWeights[BasicStat.Health] * _settings.Value.Class.HealthScale);
                classCopy.StatWeights[BasicStat.Stamina] =
                    (byte) Math.Round(classCopy.StatWeights[BasicStat.Stamina] * _settings.Value.Class.StaminaScale);
                classCopy.StatWeights[BasicStat.Magicka] =
                    (byte) Math.Round(classCopy.StatWeights[BasicStat.Magicka] * _settings.Value.Class.MagickaScale);
            }
        }

        private static void PatchNPCs()
        {
            foreach (INpcGetter npc in _loadOrder.PriorityOrder.Npc()
                .WinningOverrides()
                .Where(npc =>
                {
                    if (npc.Configuration.TemplateFlags.HasFlag(NpcConfiguration.TemplateFlag.Stats))
                        return false;

                    if (!ShouldPatchRecord(npc.EditorID, _settings.Value.NpcsToInclude,
                            _settings.Value.NpcsToExclude))
                        return false;

                    return (npc.Configuration.HealthOffset != 0 && Math.Abs(_settings.Value.NpcOffsetMults.HealthOffsetMult - 1) > 0.001 ||
                            npc.Configuration.StaminaOffset != 0 && Math.Abs(_settings.Value.NpcOffsetMults.StaminaOffsetMult - 1) > 0.001 ||
                            npc.Configuration.MagickaOffset != 0 && Math.Abs(_settings.Value.NpcOffsetMults.MagickaOffsetMult - 1) > 0.001);
                }))
            {
                var npcCopy = _patchMod.Npcs.GetOrAddAsOverride(npc);
                if (npc.FormKey == Skyrim.Npc.Player.FormKey)
                {
                    npcCopy.Configuration.HealthOffset = 0;
                    npcCopy.Configuration.StaminaOffset = 0;
                    npcCopy.Configuration.MagickaOffset = 0;
                    continue;
                }

                npcCopy.Configuration.HealthOffset = (short) Math.Round(npcCopy.Configuration.HealthOffset *
                                                                        _settings.Value.NpcOffsetMults
                                                                            .HealthOffsetMult);
                npcCopy.Configuration.StaminaOffset = (short) Math.Round(npcCopy.Configuration.StaminaOffset *
                                                                         _settings.Value.NpcOffsetMults
                                                                             .StaminaOffsetMult);
                npcCopy.Configuration.MagickaOffset = (short) Math.Round(npcCopy.Configuration.MagickaOffset *
                                                                         _settings.Value.NpcOffsetMults
                                                                             .MagickaOffsetMult);
            }
        }

        private static void PatchGameSettings()
        {
            GameSettingFloat gmstCopy =
                (GameSettingFloat) _patchMod.GameSettings.GetOrAddAsOverride(Skyrim.GameSetting.fNPCHealthLevelBonus,
                    _linkCache);
            gmstCopy.Data = _settings.Value.NpcHealthBonusPerLevel;

            gmstCopy = (GameSettingFloat) _patchMod.GameSettings.GetOrAddAsOverride(
                Skyrim.GameSetting.fCombatHealthRegenRateMult, _linkCache);
            gmstCopy.Data = _settings.Value.PlayerCombatRegenPenalties.HealthCombatRegenPenalty;

            gmstCopy = (GameSettingFloat) _patchMod.GameSettings.GetOrAddAsOverride(
                Skyrim.GameSetting.fCombatStaminaRegenRateMult, _linkCache);
            gmstCopy.Data = _settings.Value.PlayerCombatRegenPenalties.StaminaCombatRegenPenalty;

            gmstCopy = (GameSettingFloat) _patchMod.GameSettings.GetOrAddAsOverride(
                Skyrim.GameSetting.fCombatMagickaRegenRateMult, _linkCache);
            gmstCopy.Data = _settings.Value.PlayerCombatRegenPenalties.MagickaCombatRegenPenalty;
        }

        private static void PatchRaces()
        {
            foreach (IRaceGetter race in _loadOrder.PriorityOrder.Race().WinningOverrides())
            {
                if (!ShouldPatchRecord(race.EditorID, _settings.Value.RacesToInclude, _settings.Value.RacesToExclude))
                    continue;

                var raceCopy = _patchMod.Races.GetOrAddAsOverride(race);
                var raceEditorId = raceCopy.EditorID ?? string.Empty;
                var isChildRace = raceEditorId.Contains("child", StringComparison.OrdinalIgnoreCase);
                var isVampireRace = raceEditorId.Contains("vampire", StringComparison.OrdinalIgnoreCase);
                var isDlc1Race = raceEditorId.Contains("dlc1", StringComparison.OrdinalIgnoreCase);

                raceCopy.Regen[BasicStat.Health] =
                    raceCopy.Regen[BasicStat.Health] * _settings.Value.HealthRegen.Scale +
                    _settings.Value.HealthRegen.Shift;
                raceCopy.Regen[BasicStat.Stamina] =
                    raceCopy.Regen[BasicStat.Stamina] * _settings.Value.StaminaRegen.Scale +
                    _settings.Value.StaminaRegen.Shift;
                raceCopy.Regen[BasicStat.Magicka] =
                    raceCopy.Regen[BasicStat.Magicka] * _settings.Value.MagickaRegen.Scale +
                    _settings.Value.MagickaRegen.Shift;

                if (Enum.TryParse<Races>(
                    raceEditorId.Replace("Race", string.Empty).Replace("Vampire", string.Empty)
                        .Replace("Child", string.Empty),
                    true,
                    out var key))
                {
                    var stats = _settings.Value.RacesStats[key];
                    raceCopy.Starting[BasicStat.Health] = stats.Health;
                    raceCopy.Starting[BasicStat.Stamina] = stats.Stamina;
                    raceCopy.Starting[BasicStat.Magicka] = stats.Magicka;
                    raceCopy.BaseCarryWeight = stats.CarryWeight;
                    raceCopy.ActorEffect ??= new ExtendedList<IFormLinkGetter<ISpellRecordGetter>>();
                    if (isVampireRace && !isDlc1Race && _settings.Value.HealthRegen.DebuffVampires)
                    {
                        raceCopy.ActorEffect.Add(_healthRegenAbility);
                    }
                    else if (!isVampireRace)
                    {
                        raceCopy.ActorEffect.Add(_healthRegenAbility);
                    }
                }
                else
                {
                    raceCopy.Starting[BasicStat.Health] =
                        raceCopy.Starting[BasicStat.Health] * _settings.Value.CommonStats.HealthScale +
                        _settings.Value.CommonStats.HealthShift;
                    raceCopy.Starting[BasicStat.Stamina] =
                        raceCopy.Starting[BasicStat.Stamina] * _settings.Value.CommonStats.StaminaScale +
                        _settings.Value.CommonStats.StaminaShift;
                    raceCopy.Starting[BasicStat.Magicka] =
                        raceCopy.Starting[BasicStat.Magicka] * _settings.Value.CommonStats.MagickaScale +
                        _settings.Value.CommonStats.MagickaShift;
                }

                if (isChildRace)
                {
                    raceCopy.Starting[BasicStat.Health] *= _settings.Value.StatScales[ChildVampire.Child].HealthScale;
                    raceCopy.Starting[BasicStat.Stamina] *= _settings.Value.StatScales[ChildVampire.Child].StaminaScale;
                    raceCopy.Starting[BasicStat.Magicka] *= _settings.Value.StatScales[ChildVampire.Child].MagickaScale;
                    raceCopy.BaseCarryWeight *= _settings.Value.StatScales[ChildVampire.Child].CarryWeightScale;
                }

                if (isVampireRace && !isDlc1Race)
                {
                    raceCopy.Starting[BasicStat.Health] *= _settings.Value.StatScales[ChildVampire.Vampire].HealthScale;
                    raceCopy.Starting[BasicStat.Stamina] *=
                        _settings.Value.StatScales[ChildVampire.Vampire].StaminaScale;
                    raceCopy.Starting[BasicStat.Magicka] *=
                        _settings.Value.StatScales[ChildVampire.Vampire].MagickaScale;
                    raceCopy.BaseCarryWeight *= _settings.Value.StatScales[ChildVampire.Vampire].CarryWeightScale;
                }

                if (_settings.Value.UsingSurvivalMode)
                    raceCopy.BaseCarryWeight += SurvivalCarryWeightBonus;
            }
        }

        private static bool HasVokriiMagickaRecoveryEffect(IEffectGetter effect)
        {
            if (effect.Data == null)
                return false;

            IMagicEffectGetter? baseEffect;
            try
            {
                baseEffect = effect.BaseEffect.Resolve(_linkCache);
            }
            catch
            {
                return false;
            }

            return baseEffect.EditorID?.Contains(VokriiMagickaRecoveryEffectEditorId,
                StringComparison.OrdinalIgnoreCase) ?? false;
        }

        private static void PatchVokriiSpells()
        {
            if (!_settings.Value.MagickaRegen.ScaleVokriiAdditiveBuffs)
                return;

            foreach (var spell in _loadOrder.PriorityOrder.Spell().WinningOverrides())
            {
                if (!spell.Effects.Any(HasVokriiMagickaRecoveryEffect))
                    continue;

                var spellCopy = _patchMod.Spells.GetOrAddAsOverride(spell);
                foreach (var effect in spellCopy.Effects.Where(HasVokriiMagickaRecoveryEffect))
                {
                    effect.Data!.Magnitude *= _settings.Value.MagickaRegen.Scale;
                }
            }
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            _linkCache = state.LinkCache;
            _loadOrder = state.LoadOrder;
            _patchMod = state.PatchMod;
            CreateAbility();
            PatchClasses();
            PatchNPCs();
            PatchGameSettings();
            PatchRaces();
            PatchVokriiSpells();
        }
    }
}
